### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by hummat** [hummat/easy-o3d#1]
- [x] Proper `README.md`
- [x] `README.md` as interactive GitHub Pages version
- [x] More tests
- [x] Finalize `run_registration.py` script
- [x] Write `hyperopt.py` hyperparameter optimization script
- [x] Finalize `tutorial.ipynb`
- [x] Add Fast Global Registration implementation
- [x] Add RANSAC implementation
- [x] Add outlier removal
- [x] Add robust Point-To-Plane kernel option
- [x] Maybe add multiprocessing support
- [x] Maybe add multi-scale scheme
- [ ] Maybe add interactive visualization
- [x] Finalize `setup.py`
- [x] Finalize docu
